import os
import re
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import AuthorizedSession
import pygsheets
import pandas as pd
from fpdf import FPDF
import tkinter as tk
import logging
from myWhatsAppAPI import MyWhatsAppAPI
from connection import WhatsAppConnection
from pdf2image import convert_from_path
import traceback


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


def bind_tooltip(root, info_label, message):
    tooltip = None

    def show_full_message(event, msg=message):
        nonlocal tooltip

        x = info_label.winfo_rootx() + 25
        y = info_label.winfo_rooty() + info_label.winfo_height() + 5

        tooltip = tk.Toplevel(root)
        tooltip.wm_overrideredirect(True)
        tooltip.wm_geometry(f"+{x}+{y}")

        tooltip_bg = root.cget("background")
        max_width = root.winfo_width() // 2
        label = tk.Label(tooltip, text=msg, background=tooltip_bg, relief="solid", borderwidth=1, wraplength=max_width)
        label.pack()

    def hide_full_message(event):
        if tooltip:
            tooltip.destroy()

    info_label.bind("<Enter>", show_full_message)
    info_label.bind("<Leave>", hide_full_message)

    return tooltip  # Return tooltip object


def google_download_worksheet(creds: Credentials, file_id: str, sheet_name: str) -> tuple[pd.DataFrame, str]:
    """
    Connect to Google Drive and get the specified worksheet from the Google Sheets
    file as a pandas dataframe. Also filter out unuseful columns and rows with no
    table number.

    Args:
        file_id (str): the ID of the Google Sheets file.
        sheet_name (str): the name of the Google Sheets worksheet.
    Returns:
        tuple: A tuple containing the dataframe of the specified worksheet and an error message.
                If no error occurs, the error message will be an empty string.
    """
    # Connect to Google Drive and get the spreadsheet.
    logger.info(f"Getting data from Google Drive - file_id: {file_id} and sheet_name: {sheet_name}")
    try:
        client = pygsheets.authorize(custom_credentials=creds)
        spreadsheet = client.open_by_key(file_id)
        sheet = spreadsheet.worksheet_by_title(sheet_name)
        logger.info(sheet)
    except Exception as e:
        error_message = f"Error connecting to Google Drive: {e}"
        logger.error(error_message)
        return None, error_message

    # Convert the worksheet to a pandas dataframe.
    # TODO: Fix the warning generated by the conversion.
    df_dump = sheet.get_as_df(include_tailing_empty=True, has_header=True)

    # Log columns before any processing
    logger.info(f"Columns before processing: {df_dump.columns}")

    # Clean column names: strip spaces and remove non-visible characters like tabs and newlines
    df_dump.columns = [col.strip().replace("\t", "").replace("\n", "") if isinstance(col, str) else col for col in df_dump.columns]

    # Replace empty column names with a default name (Unnamed_X)
    df_dump.columns = [f"Unnamed_{i}" if col == "" else col for i, col in enumerate(df_dump.columns)]

    # Log columns after cleaning
    logger.info(f"Columns after cleaning: {df_dump.columns}")


    # Maintain only useful columns.
    cols = ["Nome", "Telefono", "Num persone", "Num tavoli", "Tavolo/i"]
    not_manadatory_cols = ["Num_spiedi"]

    try:
        df = df_dump[cols]
    except KeyError as e:
        error_message = f"Error while getting columns {cols}: {e}"
        logger.error(error_message)
        return None, error_message

    try:
        df_not_mandatory = df_dump[not_manadatory_cols]
        # Join df and df_not_mandatory
        df = df.join(df_not_mandatory)
    except KeyError as e:
        logger.warning(f"Error while getting columns {not_manadatory_cols}: {e}")

    logger.info(f"Dataframe cols: {df.columns}")


    df = df.apply(lambda x: x.astype(str) if x.dtype == "object" else x)
    # Replace empty strings with pd.NA.
    df = df.replace("", pd.NA)
    # Drop rows with no 'Num tavoli' value.
    df = df[df["Num tavoli"].notna()]
    df = df.infer_objects()

    return df, ""


def google_generate_pdf_map(creds, file_id, sheet_id, output_dir, filename,
                            map_range: str = "t1:y50") -> None:
    """
    Generate a PDF of a specific range from a Google Sheet.

    Args:
        file_id (str): The ID of the Google Sheet file.
        sheet_id (str): The ID of the specific sheet within the Google Sheet file.
        output_dir (str): The directory to save the output files.
        filename (str): The base name of the output files (without extension).

    Raises:
        Exception: If there is an issue downloading the PDF or converting it to PNG.

    Returns:
        pdf_file_path (str): The path to the generated PDF file.
    """

    dwn_url = (
        f"https://docs.google.com/spreadsheets/d/{file_id}"
        f"/export?format=pdf&gid={sheet_id}"
        f"&range={map_range}"
        "&scale=4&fith=true"
        "&horizontal_alignment=CENTER&vertical_alignment=TOP"
        "&gridlines=false"
    )

    authed_session = AuthorizedSession(creds)
    if not authed_session:
        raise Exception("Failed to authenticate with Google.")
    response = authed_session.get(dwn_url)
    if response.status_code != 200:
        raise Exception(
            f"Failed to download PDF. Status code: {response.status_code}")

    # Create the output directory if it doesn't exist.
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Output the PDF file.
    pdf_file_path = os.path.join(output_dir, f"{filename}.pdf")

    with open(pdf_file_path, "wb") as f:
        f.write(response.content)

    print(f"File {pdf_file_path} written.")

    # Convert PDF to PNG
    pages = convert_from_path(pdf_file_path, dpi=300)
    if len(pages) != 1:
        raise Exception(
            "PDF to PNG conversion resulted in more than one page.")
    png_file_path = os.path.join(output_dir, f"{filename}.png")
    pages[0].save(png_file_path, 'PNG')
    print(f"File {png_file_path} written.")

    return pdf_file_path





def generate_table_labels_pdf(
        df: pd.DataFrame, filename: str, output_dir: str) -> None:
    """
    Generate a PDF containing pages with labels to attach to booked tables.

    Precondition:
    This function relies on the "Nome" and "Num tavoli" columns of the DataFrame.

    Args:
        df (pd.DataFrame): DataFrame containing booking information.
        filename (str): Name of the output PDF file (without extension).
        output_dir (str): Output directory path.
        booked_table_ids (list): List of booked table IDs.


    Returns:
        pdf_file_path (str): The path to the generated PDF file.
    """

    df = df.dropna(subset=["Tavolo/i"])
    df = df[df["Tavolo/i"].str.strip() != ""]

    # Extract the first table ID from "Tavolo/i" column and add separate columns for sorting
    df['first_table_id'] = df['Tavolo/i'].apply(lambda x: x.split(";")[0])
    df['numeric_part'] = df['first_table_id'].apply(lambda x: extract_number_and_letter(x)[0])
    df['letter_part'] = df['first_table_id'].apply(lambda x: extract_number_and_letter(x)[1])
    # Sort DataFrame by the numeric and letter parts of the first table ID
    df = df.sort_values(by=['numeric_part', 'letter_part'])

    pdf = FPDF(orientation="L", format="A4")

    for _, row in df.iterrows():

        pdf.add_page()

        # Prenotato label with smaller font size
        pdf.set_font('Arial', 'B', 60)
        pdf.cell(w=0, h=40, txt='PRENOTATO', align="C", ln=2)

        name = row['Nome'].upper()
        tables_num = int(row["Num tavoli"])
        print(f"Printing page for {name} with {tables_num} tables...")

        # Adjust font size for the name based on its length
        name_font_size = 100
        max_name_length = 10  # Define the maximum length for the name to fit in one line
        if len(name) > max_name_length:
            name_font_size = max(30, 100 - (len(name) - max_name_length) * 5)

        pdf.set_font('Arial', 'B', name_font_size)
        pdf.cell(w=0, h=70, align="C", txt=name, ln=2)

        # Number of tables and table IDs
        try:
            booked_table_ids = row["Tavolo/i"].split(";")
        except AttributeError:
            print("Error: Tavolo/i column not found in the row.")
            booked_table_ids = []
        table_ids_text = '-'.join(map(str, booked_table_ids))
        pdf.set_font('Arial', 'B', 50)

        # Number of tables and table IDs combined
        pdf.cell(w=0, h=25, align="C", txt=f"{tables_num} TAVOL{'I' if tables_num > 1 else 'O'}", ln=2)
        pdf.cell(w=0, h=25, align="C", txt=table_ids_text, ln=2)
        pdf.set_font('Arial', 'B', 50)

        # Check if "Num spiedi" column exists
        if "Num spiedi" in df.columns and not pd.isna(row["Num spiedi"]):
            num_spiedi = row["Num spiedi"]
            pdf.set_font('Arial', 'B', 20)
            pdf.cell(w=0, h=10, align="C", txt=f"{num_spiedi} SPIEDI", ln=2)

    # Create the output directory if it doesn't exist.
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    # Output the file.
    pdf_file_path = os.path.join(output_dir, f"{filename}.pdf")
    pdf.output(pdf_file_path, 'F')
    print(f"File {pdf_file_path} written.")

    return pdf_file_path


def extract_number_and_letter(value):
    match = re.match(r"(\d+)([A-Z])", value)
    if match:
        number, letter = match.groups()
        return int(number), letter
    return 0, ''  # Default return if the pattern does not match


def send_whatsapp_messages(connection: WhatsAppConnection, df: pd.DataFrame,
                           day_string: str, send_image: bool,
                           template_name: str = "image_2025",
                           api_version: str = "v25.0",
                           log_file: str = "wp_api.log",
                           media_log_file: str = "wp_media_uploads.log") -> bool:
    """
    Send WhatsApp messages to customers with booking information.

    Args:
        connection (WhatsAppConnection): Active WhatsApp connection.
        df (pd.DataFrame): DataFrame containing customer booking information.
        day_string (str): Human-readable day label used in the message template
                          (e.g. "Giovedì 03 Luglio").
        send_image (bool): Whether to include the seating map image.
        template_name (str): WhatsApp template name to use.
        api_version (str): Meta Graph API version (e.g. "v25.0").
        log_file (str): Path for the API call log file.
        media_log_file (str): Path for the media upload log file.

    Returns:
        bool: True if all messages were sent successfully, False otherwise.
    """
    image_filename = f"{os.path.dirname(__file__)}/empty-map.png"
    wa = MyWhatsAppAPI(connection, api_version=api_version,
                       log_file=log_file, media_log_file=media_log_file)
    media_id = wa.upload_media(image_filename, 'image/png')
    skipped = []

    for _, row in df.iterrows():
        name = row['Nome']
        telephone = row["Telefono"]
        num_tables = int(row["Num tavoli"])
        tables = row["Tavolo/i"].split(";")
        plural = "i" if num_tables > 1 else "o"
        tables_string = f"tavol{plural} *" + ", ".join(tables) + "*"

        logger.info(f"Sending message to {name} ({telephone})")

        try:
            body_template_parameters = [
                {"type": "text", "text": day_string},
                {"type": "text", "text": str(num_tables)},
                {"type": "text", "text": plural},
                {"type": "text", "text": name},
                {"type": "text", "text": tables_string}
            ]
            success = wa.send_media_template(
                telephone, media_id, 'IMAGE', template_name, 'it',
                body_template_parameters
            )
            if not success:
                raise Exception("Failed to send template message")

        except Exception:
            traceback.print_exc()
            skipped.append(row)
            print("Skipped")

    if skipped:
        print("Skipped:")
        print(pd.DataFrame(skipped))
        return False

    return True
